--q1 - Retrieve the names of employees along with their department names from two tables, employees and departments, using a join.
SELECT EMPLOYEES.NAME, DEPARTMENTS.NAME FROM EMPLOYEES
INNER JOIN DEPARTMENTS EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID; 

-- q2- Retrieve all employees and their projects, including those who are not assigned to any project.
SELECT EMPLOYEES.NAME, PROJECTS.NAME FROM EMPLOYEES 
LEFT JOIN EMPLOYEES_PROJECT ON EMPLOYEES.EMPLOYEES_ID = EMPLOYEES_PROJECT.EMPLOYEES_ID;
LEFT JOIN PROEJECTS ON EMPLOYEES_PROJECT.PROJECT_ID = PROEJECTS.PROJECT_ID;

-- q3 - Question: Retrieve the names and salaries of employees who work in the 'IT' department and have a salary greater than $70,000.
-- method 1 
SELECT NAME, SALARY FROM EMPLOYEES WHERE SALARY > 70000 AND DEPARTMENT_ID=(SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME='IT');
-- method 2 
SELECT EMPLOYEES.NAME, EMPLOYEES.SALARY FROM EMPLOYEES 
JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID 
WHERE DEPARTMENTS.DEPARTMENT_NAME = 'IT' AND EMPLOYEES.SALARY > 70000;


-- q4 - Retrieve the names of employees and their managers using aliases 
SELECT E.NAME AS EMPLOYEE_NAME, M.NAME AS MANAGER_NAME,
FROM EMPLOYEES E
LEFT JOIN EMPLOYEES M ON E.MANAGER_ID = M.EMPLOYEE_ID; 


