SELECT * FROM EMPLOYEES;
SELECT NAME FROM EMPLOYEES WHERE SALARY > 50000 ORDER BY SALARY DESC;
SELECT EMPLOYEES.NAME, DEPARTMENT.NAME FROM EMPLOYEES INNER JOIN DEPARTMENT ON EMPLOYEE.DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID;
SELECT avg(SALARY) AS AVERAGE_SALARY FROM EMPLOYEES;
SELECT NAME FROM EMPLOYEES WHERE SALARY between 40000 AND 60000 AND DEPARTMENT_ID=(SELECT DEPARTMENT_ID FROM DEPARTMENT WHERE DEPARTMENT_NAME = "IT")
SELECT NAME, SALARY, HIRE_DATE FROM EMPLOYEES order by DEPARTMENT_ID asc, HIRE_DATE desc;
SELECT NAME, SALARY FROM EMPLOYEES WHERE COMMISSION_PERCENTAGE IS NOT NULL order by COMMISSION_PERCENTAGE desc
SELECT NAME FROM EMPLOYEES WHERE NAME LIKE 'A%';
SELECT NAME FROM EMPLOYEES ORDER BY LOWER(NAME); 
SELECT NAME FROM EMPLOYEES WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME IN ('IT', 'HR'));
SELECT NAME, JOB_TITLE FROM EMPLOYEES
order by 
	CASE 
    	WHEN JOB_TITLE = 'MANAGER' THEN 1
        WHEN JOB_TITLE = 'ANALYST' THEN 2 
        WHEN JOB_TITLE = 'CLERK' THEN 3 
        WHEN JOB_TITLE = 'PRESIDENT' THEN 4 
        WHEN JOB_TITLE = 'SALESMAN' THEN 5
        WHEN JOB_TITLE = 'TECHNICIAN' THEN 6
        ELSE 7
	END; 
    
    
SELECT NAME FROM EMPLOYEES WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME='SALES'));
SELECT NAME, HIRE_DATE FROM EMPLOYEES order by HIRE_DATE ASC, HIRE_DATE IS NULL DESC;

